config {
    type: "incremental",
    uniqueKey: ["id", "snapshot_date"],
    protected: true,
    bigquery: {
        partitionBy: "snapshot_date"
    }
}

WITH
get_max_snapshot_date AS (
  SELECT
    MAX(snapshot_date) AS max_snapshot_date
  FROM
    ${self()} 
)
SELECT
  *,
  CURRENT_DATE() AS snapshot_date
FROM
  ${ref("linkedin_followers_by_geo")} 
${when(incremental(), 'WHERE CURRENT_DATE() > (SELECT DATE(max_snapshot_date) FROM get_max_snapshot_date)')}